// SOULENGINE
export const SOULENGINESTATUS_TITLESCREEN = 'SOULENGINESTATUS_TITLESCREEN';

// SOULCOUNTER
export const SOULCOUNTER_INCREMENT = 'SOULCOUNTER_INCREMENT';
export const SOULCOUNTER_RESET = 'SOULCOUNTER_RESET';